import matplotlib
matplotlib.use('TkAgg') # Necessary for GUI display on WSL
import matplotlib.pyplot as plt
import pandas as pd

# 1. Loading data
try:
    # Path to the CSV generated by the C++ code
    df = pd.read_csv('build/solar_system_atlas.csv')
except FileNotFoundError:
    print("Error: 'solar_system_atlas.csv' not found in 'build/' directory.")
    exit()

# 2. Figure configuration
plt.figure(figsize=(10, 10))
# plt.style.use('dark_background')

# 3. Plotting trajectories
bodies = df['name'].unique()
# Color palette for the planets
colors = ['yellow', 'gray', 'orange', 'blue', 'red', 'brown', 'gold', 'cyan', 'navy']

# Astronomical Unit in meters
AU = 1.496e11

for body, color in zip(bodies, colors):
    data = df[df['name'] == body]
    
    # Convert vectors \vec{r} coordinates from meters to AU
    x_au = data['x'] / AU
    y_au = data['y'] / AU
    
    # Plot the full trajectory path
    plt.plot(x_au, y_au, label=body, color=color, linewidth=1, alpha=0.8)
    
    # Mark the current position with a dot
    plt.scatter(x_au.iloc[-1], y_au.iloc[-1], color=color, s=30)

# 4. Axis and Grid styling
# Draw X and Y axes passing through the origin (0,0)
plt.axhline(0, color='white', linewidth=0.5, alpha=0.3)
plt.axvline(0, color='white', linewidth=0.5, alpha=0.3)

plt.title("N-Body Solar System Simulation (165 years)", fontsize=15, pad=20)
plt.xlabel("x distance [AU]", fontsize=12)
plt.ylabel("y distance [AU]", fontsize=12)

# Set limits to see Neptune (approx 30 AU)
limit = 35 
plt.xlim(-limit, limit)
plt.ylim(-limit, limit)

plt.legend(loc='upper right', bbox_to_anchor=(1.15, 1.0))
plt.grid(True, linestyle=':', alpha=0.4)
plt.gca().set_aspect('equal', adjustable='box') # Keep circles as circles

# To zoom on inner planets, uncomment these lines:
# plt.xlim(-2, 2)
# plt.ylim(-2, 2)

plt.tight_layout()
plt.show()